import React, { Children } from 'react'
import Head from 'next/head'
import Navigation from './Navigation'

type Props = {
    children: JSX.Element
}

const Layout = ({children}  : Props) => {
  return (
<>
<Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <Navigation/>
  {children}
  <footer className="">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          
        </a>
      </footer>
  </>
  )
}

export default Layout